module ModelUn
  US_STATES = [
    [{:full => 'ALABAMA',                         :abbr => 'AL'}],
    [{:full => 'ALASKA',                          :abbr => 'AK'}],
    [{:full => 'AMERICAN SAMOA',                  :abbr => 'AS'}],
    [{:full => 'ARIZONA',                         :abbr => 'AZ'}],
    [{:full => 'ARKANSAS',                        :abbr => 'AR'}],
    [{:full => 'CALIFORNIA',                      :abbr => 'CA'}],
    [{:full => 'COLORADO',                        :abbr => 'CO'}],
    [{:full => 'CONNECTICUT',                     :abbr => 'CT'}],
    [{:full => 'DELAWARE',                        :abbr => 'DE'}],
    [{:full => 'DISTRICT OF COLUMBIA',            :abbr => 'DC'}],
    [{:full => 'FEDERATED STATES OF MICRONESIA',  :abbr => 'FM'}],
    [{:full => 'FLORIDA',                         :abbr => 'FL'}],
    [{:full => 'GEORGIA',                         :abbr => 'GA'}],
    [{:full => 'GUAM',                            :abbr => 'GU'}],
    [{:full => 'HAWAII',                          :abbr => 'HI'}],
    [{:full => 'IDAHO',                           :abbr => 'ID'}],
    [{:full => 'ILLINOIS',                        :abbr => 'IL'}],
    [{:full => 'INDIANA',                         :abbr => 'IN'}],
    [{:full => 'IOWA',                            :abbr => 'IA'}],
    [{:full => 'KANSAS',                          :abbr => 'KS'}],
    [{:full => 'KENTUCKY',                        :abbr => 'KY'}],
    [{:full => 'LOUISIANA',                       :abbr => 'LA'}],
    [{:full => 'MAINE',                           :abbr => 'ME'}],
    [{:full => 'MARSHALL ISLANDS',                :abbr => 'MH'}],
    [{:full => 'MARYLAND',                        :abbr => 'MD'}],
    [{:full => 'MASSACHUSETTS',                   :abbr => 'MA'}],
    [{:full => 'MICHIGAN',                        :abbr => 'MI'}],
    [{:full => 'MINNESOTA',                       :abbr => 'MN'}],
    [{:full => 'MISSISSIPPI',                     :abbr => 'MS'}],
    [{:full => 'MISSOURI',                        :abbr => 'MO'}],
    [{:full => 'MONTANA',                         :abbr => 'MT'}],
    [{:full => 'NEBRASKA',                        :abbr => 'NE'}],
    [{:full => 'NEVADA',                          :abbr => 'NV'}],
    [{:full => 'NEW HAMPSHIRE',                   :abbr => 'NH'}],
    [{:full => 'NEW JERSEY',                      :abbr => 'NJ'}],
    [{:full => 'NEW MEXICO',                      :abbr => 'NM'}],
    [{:full => 'NEW YORK',                        :abbr => 'NY'}],
    [{:full => 'NORTH CAROLINA',                  :abbr => 'NC'}],
    [{:full => 'NORTH DAKOTA',                    :abbr => 'ND'}],
    [{:full => 'NORTHERN MARIANA ISLANDS',        :abbr => 'MP'}],
    [{:full => 'OHIO',                            :abbr => 'OH'}],
    [{:full => 'OKLAHOMA',                        :abbr => 'OK'}],
    [{:full => 'OREGON',                          :abbr => 'OR'}],
    [{:full => 'PALAU',                           :abbr => 'PW'}],
    [{:full => 'PENNSYLVANIA',                    :abbr => 'PA'}],
    [{:full => 'PUERTO RICO',                     :abbr => 'PR'}],
    [{:full => 'RHODE ISLAND',                    :abbr => 'RI'}],
    [{:full => 'SOUTH CAROLINA',                  :abbr => 'SC'}],
    [{:full => 'SOUTH DAKOTA',                    :abbr => 'SD'}],
    [{:full => 'TENNESSEE',                       :abbr => 'TN'}],
    [{:full => 'TEXAS',                           :abbr => 'TX'}],
    [{:full => 'UTAH',                            :abbr => 'UT'}],
    [{:full => 'VERMONT',                         :abbr => 'VT'}],
    [{:full => 'VIRGIN ISLANDS',                  :abbr => 'VI'}],
    [{:full => 'VIRGINIA',                        :abbr => 'VA'}],
    [{:full => 'WASHINGTON',                      :abbr => 'WA'}],
    [{:full => 'WEST VIRGINIA',                   :abbr => 'WV'}],
    [{:full => 'WISCONSIN',                       :abbr => 'WI'}],
    [{:full => 'WYOMING',                         :abbr => 'WY'}]
  ]
  
end
