module ModelUN
  US_STATE_ABBR = [
    'AL',
    'AK',
    'AS',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'DC',
    'FM',
    'FL',
    'GA',
    'GU',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MH',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'MP',
    'OH',
    'OK',
    'OR',
    'PW',
    'PA',
    'PR',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VI',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY'
  ]
  
  
  US_STATE_NAMES = [
     'ALABAMA',                         
     'ALASKA',                          
     'AMERICAN SAMOA',                  
     'ARIZONA',                         
     'ARKANSAS',                        
     'CALIFORNIA',                      
     'COLORADO',                        
     'CONNECTICUT',                     
     'DELAWARE',                        
     'DISTRICT OF COLUMBIA',            
     'FEDERATED STATES OF MICRONESIA',  
     'FLORIDA',                         
     'GEORGIA',                         
     'GUAM',                            
     'HAWAII',                          
     'IDAHO',                           
     'ILLINOIS',                        
     'INDIANA',                         
     'IOWA',                            
     'KANSAS',                          
     'KENTUCKY',                        
     'LOUISIANA',                       
     'MAINE',                           
     'MARSHALL ISLANDS',                
     'MARYLAND',                        
     'MASSACHUSETTS',                   
     'MICHIGAN',                        
     'MINNESOTA',                       
     'MISSISSIPPI',                     
     'MISSOURI',                        
     'MONTANA',                         
     'NEBRASKA',                        
     'NEVADA',                          
     'NEW HAMPSHIRE',                   
     'NEW JERSEY',                      
     'NEW MEXICO',                      
     'NEW YORK',                        
     'NORTH CAROLINA',                  
     'NORTH DAKOTA',                    
     'NORTHERN MARIANA ISLANDS',        
     'OHIO',                            
     'OKLAHOMA',                        
     'OREGON',                          
     'PALAU',                           
     'PENNSYLVANIA',                    
     'PUERTO RICO',                     
     'RHODE ISLAND',                    
     'SOUTH CAROLINA',                  
     'SOUTH DAKOTA',                    
     'TENNESSEE',                       
     'TEXAS',                           
     'UTAH',                            
     'VERMONT',                         
     'VIRGIN ISLANDS',                  
     'VIRGINIA',                        
     'WASHINGTON',                      
     'WEST VIRGINIA',                   
     'WISCONSIN',                       
     'WYOMING',                         
   ]
  
  US_STATES = [
    {'full' => 'ALABAMA',                         'abbr' => 'AL'},
    {'full' => 'ALASKA',                          'abbr' => 'AK'},
    {'full' => 'AMERICAN SAMOA',                  'abbr' => 'AS'},
    {'full' => 'ARIZONA',                         'abbr' => 'AZ'},
    {'full' => 'ARKANSAS',                        'abbr' => 'AR'},
    {'full' => 'CALIFORNIA',                      'abbr' => 'CA'},
    {'full' => 'COLORADO',                        'abbr' => 'CO'},
    {'full' => 'CONNECTICUT',                     'abbr' => 'CT'},
    {'full' => 'DELAWARE',                        'abbr' => 'DE'},
    {'full' => 'DISTRICT OF COLUMBIA',            'abbr' => 'DC'},
    {'full' => 'FEDERATED STATES OF MICRONESIA',  'abbr' => 'FM'},
    {'full' => 'FLORIDA',                         'abbr' => 'FL'},
    {'full' => 'GEORGIA',                         'abbr' => 'GA'},
    {'full' => 'GUAM',                            'abbr' => 'GU'},
    {'full' => 'HAWAII',                          'abbr' => 'HI'},
    {'full' => 'IDAHO',                           'abbr' => 'ID'},
    {'full' => 'ILLINOIS',                        'abbr' => 'IL'},
    {'full' => 'INDIANA',                         'abbr' => 'IN'},
    {'full' => 'IOWA',                            'abbr' => 'IA'},
    {'full' => 'KANSAS',                          'abbr' => 'KS'},
    {'full' => 'KENTUCKY',                        'abbr' => 'KY'},
    {'full' => 'LOUISIANA',                       'abbr' => 'LA'},
    {'full' => 'MAINE',                           'abbr' => 'ME'},
    {'full' => 'MARSHALL ISLANDS',                'abbr' => 'MH'},
    {'full' => 'MARYLAND',                        'abbr' => 'MD'},
    {'full' => 'MASSACHUSETTS',                   'abbr' => 'MA'},
    {'full' => 'MICHIGAN',                        'abbr' => 'MI'},
    {'full' => 'MINNESOTA',                       'abbr' => 'MN'},
    {'full' => 'MISSISSIPPI',                     'abbr' => 'MS'},
    {'full' => 'MISSOURI',                        'abbr' => 'MO'},
    {'full' => 'MONTANA',                         'abbr' => 'MT'},
    {'full' => 'NEBRASKA',                        'abbr' => 'NE'},
    {'full' => 'NEVADA',                          'abbr' => 'NV'},
    {'full' => 'NEW HAMPSHIRE',                   'abbr' => 'NH'},
    {'full' => 'NEW JERSEY',                      'abbr' => 'NJ'},
    {'full' => 'NEW MEXICO',                      'abbr' => 'NM'},
    {'full' => 'NEW YORK',                        'abbr' => 'NY'},
    {'full' => 'NORTH CAROLINA',                  'abbr' => 'NC'},
    {'full' => 'NORTH DAKOTA',                    'abbr' => 'ND'},
    {'full' => 'NORTHERN MARIANA ISLANDS',        'abbr' => 'MP'},
    {'full' => 'OHIO',                            'abbr' => 'OH'},
    {'full' => 'OKLAHOMA',                        'abbr' => 'OK'},
    {'full' => 'OREGON',                          'abbr' => 'OR'},
    {'full' => 'PALAU',                           'abbr' => 'PW'},
    {'full' => 'PENNSYLVANIA',                    'abbr' => 'PA'},
    {'full' => 'PUERTO RICO',                     'abbr' => 'PR'},
    {'full' => 'RHODE ISLAND',                    'abbr' => 'RI'},
    {'full' => 'SOUTH CAROLINA',                  'abbr' => 'SC'},
    {'full' => 'SOUTH DAKOTA',                    'abbr' => 'SD'},
    {'full' => 'TENNESSEE',                       'abbr' => 'TN'},
    {'full' => 'TEXAS',                           'abbr' => 'TX'},
    {'full' => 'UTAH',                            'abbr' => 'UT'},
    {'full' => 'VERMONT',                         'abbr' => 'VT'},
    {'full' => 'VIRGIN ISLANDS',                  'abbr' => 'VI'},
    {'full' => 'VIRGINIA',                        'abbr' => 'VA'},
    {'full' => 'WASHINGTON',                      'abbr' => 'WA'},
    {'full' => 'WEST VIRGINIA',                   'abbr' => 'WV'},
    {'full' => 'WISCONSIN',                       'abbr' => 'WI'},
    {'full' => 'WYOMING',                         'abbr' => 'WY'}
  ]
  
  
  NATO_COUNTRY_NAMES = [
    "AFGHANISTAN",
    "ALAND ISLANDS",
    "ALBANIA",
    "ALGERIA",
    "AMERICAN SAMOA",
    "ANDORRA",
    "ANGOLA",
    "ANGUILLA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "ARUBA",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "BAHAMAS",
    "BAHRAIN",
    "BANGLADESH",
    "BARBADOS",
    "BELARUS",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BERMUDA",
    "BHUTAN",
    "BOLIVIA (PLURINATIONAL STATE OF)",
    "BONAIRE, SAINT EUSTATIUS AND SABA",
    "BOSNIA AND HERZEGOVINA",
    "BOTSWANA",
    "BRAZIL",
    "BRITISH VIRGIN ISLANDS",
    "BRUNEI DARUSSALAM",
    "BULGARIA",
    "BURKINA FASO",
    "BURUNDI",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CAPE VERDE",
    "CAYMAN ISLANDS",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "CHILE",
    "CHINA",
    "CHINA, HONG KONG SPECIAL ADMINISTRATIVE REGION",
    "CHINA, MACAO SPECIAL ADMINISTRATIVE REGION",
    "COLOMBIA",
    "COMOROS",
    "CONGO",
    "COOK ISLANDS",
    "COSTA RICA",
    "COTE D'IVOIRE",
    "CROATIA",
    "CUBA",
    "CURAÇAO",
    "CYPRUS",
    "CZECH REPUBLIC",
    "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
    "DEMOCRATIC REPUBLIC OF THE CONGO",
    "DENMARK",
    "DJIBOUTI",
    "DOMINICA",
    "DOMINICAN REPUBLIC",
    "ECUADOR",
    "EGYPT",
    "EL SALVADOR",
    "EQUATORIAL GUINEA",
    "ERITREA",
    "ESTONIA",
    "ETHIOPIA",
    "FAEROE ISLANDS",
    "FALKLAND ISLANDS (MALVINAS)",
    "FIJI",
    "FINLAND",
    "FRANCE",
    "FRENCH GUIANA",
    "FRENCH POLYNESIA",
    "GABON",
    "GAMBIA",
    "GEORGIA",
    "GERMANY",
    "GHANA",
    "GIBRALTAR",
    "GREECE",
    "GREENLAND",
    "GRENADA",
    "GUADELOUPE",
    "GUAM",
    "GUATEMALA",
    "GUERNSEY",
    "GUINEA",
    "GUINEA-BISSAU",
    "GUYANA",
    "HAITI",
    "HOLY SEE",
    "HONDURAS",
    "HUNGARY",
    "ICELAND",
    "INDIA",
    "INDONESIA",
    "IRAN (ISLAMIC REPUBLIC OF)",
    "IRAQ",
    "IRELAND",
    "ISLE OF MAN",
    "ISRAEL",
    "ITALY",
    "JAMAICA",
    "JAPAN",
    "JERSEY	",
    "JORDAN",
    "KAZAKHSTAN",
    "KENYA",
    "KIRIBATI",
    "KUWAIT",
    "KYRGYZSTAN",
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    "LATVIA",
    "LEBANON",
    "LESOTHO",
    "LIBERIA",
    "LIBYAN ARAB JAMAHIRIYA",
    "LIECHTENSTEIN",
    "LITHUANIA",
    "LUXEMBOURG",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALDIVES",
    "MALI",
    "MALTA",
    "MARSHALL ISLANDS",
    "MARTINIQUE",
    "MAURITANIA",
    "MAURITIUS",
    "MAYOTTE	",
    "MEXICO",
    "MICRONESIA (FEDERATED STATES OF)",
    "MONACO",
    "MONGOLIA",
    "MONTENEGRO",
    "MONTSERRAT",
    "MOROCCO",
    "MOZAMBIQUE",
    "MYANMAR",
    "NAMIBIA",
    "NAURU",
    "NEPAL",
    "NETHERLANDS",
    "NEW CALEDONIA",
    "NEW ZEALAND",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NIUE",
    "NORFOLK ISLAND",
    "NORTHERN MARIANA ISLANDS",
    "NORWAY",
    "OCCUPIED PALESTINIAN TERRITORY",
    "OMAN",
    "PAKISTAN",
    "PALAU",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "PHILIPPINES",
    "PITCAIRN",
    "POLAND",
    "PORTUGAL",
    "PUERTO RICO",
    "QATAR",
    "REPUBLIC OF KOREA",
    "REPUBLIC OF MOLDOVA",
    "REUNION",
    "ROMANIA",
    "RUSSIAN FEDERATION",
    "RWANDA",
    "SAINT-BARTHELEMY",
    "SAINT HELENA",
    "SAINT KITTS AND NEVIS",
    "SAINT LUCIA",
    "SAINT-MARTIN (FRENCH PART)",
    "SAINT PIERRE AND MIQUELON",
    "SAINT VINCENT AND THE GRENADINES",
    "SAMOA",
    "SAN MARINO",
    "SAO TOME AND PRINCIPE",
    "SAUDI ARABIA",
    "SENEGAL",
    "SERBIA",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPORE",
    "SINT MAARTEN (DUTCH PART)",
    "SLOVAKIA",
    "SLOVENIA",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SOUTH AFRICA",
    "SPAIN",
    "SRI LANKA",
    "SUDAN",
    "SURINAME",
    "SVALBARD AND JAN MAYEN ISLANDS",
    "SWAZILAND",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIAN ARAB REPUBLIC",
    "TAJIKISTAN",
    "THAILAND",
    "THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA",
    "TIMOR-LESTE",
    "TOGO",
    "TOKELAU",
    "TONGA",
    "TRINIDAD AND TOBAGO",
    "TUNISIA",
    "TURKEY",
    "TURKMENISTAN",
    "TURKS AND CAICOS ISLANDS",
    "TUVALU",
    "UGANDA",
    "UKRAINE",
    "UNITED ARAB EMIRATES",
    "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
    "UNITED REPUBLIC OF TANZANIA",
    "UNITED STATES OF AMERICA",
    "UNITED STATES VIRGIN ISLANDS",
    "URUGUAY",
    "UZBEKISTAN",
    "VANUATU",
    "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    "VIET NAM",
    "WALLIS AND FUTUNA ISLANDS",
    "WESTERN SAHARA",
    "YEMEN",
    "ZAMBIA",
    "ZIMBABWE"
  ]
  
  NATO_ABBR = [
    'AFG',
    'ALA',
    'ALB',
    'DZA',
    'ASM',
    'AND',
    'AGO',
    'AIA',
    'ATG',
    'ARG',
    'ARM',
    'ABW',
    'AUS',
    'AUT',
    'AZE',
    'BHS',
    'BHR',
    'BGD',
    'BRB',
    'BLR',
    'BEL',
    'BLZ',
    'BEN',
    'BMU',
    'BTN',
    'BOL',
    'BES',
    'BIH',
    'BWA',
    'BRA',
    'VGB',
    'BRN',
    'BGR',
    'BFA',
    'BDI',
    'KHM',
    'CMR',
    'CAN',
    'CPV',
    'CYM',
    'CAF',
    'TCD',
    'CHL',
    'CHN',
    'HKG',
    'MAC',
    'COL',
    'COM',
    'COG',
    'COK',
    'CRI',
    'CIV',
    'HRV',
    'CUB',
    'CUW',
    'CYP',
    'CZE',
    'PRK',
    'COD',
    'DNK',
    'DJI',
    'DMA',
    'DOM',
    'ECU',
    'EGY',
    'SLV',
    'GNQ',
    'ERI',
    'EST',
    'ETH',
    'FRO',
    'FLK',
    'FJI',
    'FIN',
    'FRA',
    'GUF',
    'PYF',
    'GAB',
    'GMB',
    'GEO',
    'DEU',
    'GHA',
    'GIB',
    'GRC',
    'GRL',
    'GRD',
    'GLP',
    'GUM',
    'GTM',
    'GGY',
    'GIN',
    'GNB',
    'GUY',
    'HTI',
    'VAT',
    'HND',
    'HUN',
    'ISL',
    'IND',
    'IDN',
    'IRN',
    'IRQ',
    'IRL',
    'IMN',
    'ISR',
    'ITA',
    'JAM',
    'JPN',
    'JEY',
    'JOR',
    'KAZ',
    'KEN',
    'KIR',
    'KWT',
    'KGZ',
    'LAO',
    'LVA',
    'LBN',
    'LSO',
    'LBR',
    'LBY',
    'LIE',
    'LTU',
    'LUX',
    'MDG',
    'MWI',
    'MYS',
    'MDV',
    'MLI',
    'MLT',
    'MHL',
    'MTQ',
    'MRT',
    'MUS',
    'MYT',
    'MEX',
    'FSM',
    'MCO',
    'MNG',
    'MNE',
    'MSR',
    'MAR',
    'MOZ',
    'MMR',
    'NAM',
    'NRU',
    'NPL',
    'NLD',
    'NCL',
    'NZL',
    'NIC',
    'NER',
    'NGA',
    'NIU',
    'NFK',
    'MNP',
    'NOR',
    'PSE',
    'OMN',
    'PAK',
    'PLW',
    'PAN',
    'PNG',
    'PRY',
    'PER',
    'PHL',
    'PCN',
    'POL',
    'PRT',
    'PRI',
    'QAT',
    'KOR',
    'MDA',
    'REU',
    'ROU',
    'RUS',
    'RWA',
    'BLM',
    'SHN',
    'KNA',
    'LCA',
    'MAF',
    'SPM',
    'VCT',
    'WSM',
    'SMR',
    'STP',
    'SAU',
    'SEN',
    'SRB',
    'SYC',
    'SLE',
    'SGP',
    'SXM',
    'SVK',
    'SVN',
    'SLB',
    'SOM',
    'ZAF',
    'ESP',
    'LKA',
    'SDN',
    'SUR',
    'SJM',
    'SWZ',
    'SWE',
    'CHE',
    'SYR',
    'TJK',
    'THA',
    'MKD',
    'TLS',
    'TGO',
    'TKL',
    'TON',
    'TTO',
    'TUN',
    'TUR',
    'TKM',
    'TCA',
    'TUV',
    'UGA',
    'UKR',
    'ARE',
    'GBR',
    'TZA',
    'USA',
    'VIR',
    'URY',
    'UZB',
    'VUT',
    'VEN',
    'VNM',
    'WLF',
    'ESH',
    'YEM',
    'ZMB',
    'ZWE'
  ]
  
end
